### ISSUE TITLE
SIGSEGV flake in TestGameServerHealthyAfterDeletingPodWhileOneExtensionsDown

### ISSUE THREAD

**Issue by zmerlynn** [googleforgames/agones#2992]
From https://github.com/googleforgames/agones/pull/2979#issuecomment-1441100370:

```
generic-1.24: Step #1 - "e2e-feature-gates": --- FAIL: TestGameServerHealthyAfterDeletingPodWhileOneExtensionsDown (0.15s)
generic-1.24: Step #1 - "e2e-feature-gates": panic: runtime error: invalid memory address or nil pointer dereference [recovered]
generic-1.24: Step #1 - "e2e-feature-gates": 	panic: runtime error: invalid memory address or nil pointer dereference
generic-1.24: Step #1 - "e2e-feature-gates": [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x20f9f70]
generic-1.24: Step #1 - "e2e-feature-gates": 
generic-1.24: Step #1 - "e2e-feature-gates": goroutine 9 [running]:
generic-1.24: Step #1 - "e2e-feature-gates": testing.tRunner.func1.2({0x22a4200, 0x340b020})
generic-1.24: Step #1 - "e2e-feature-gates": 	/usr/local/go/src/testing/testing.go:1396 +0x372
generic-1.24: Step #1 - "e2e-feature-gates": testing.tRunner.func1()
generic-1.24: Step #1 - "e2e-feature-gates": 	/usr/local/go/src/testing/testing.go:1399 +0x5f0
generic-1.24: Step #1 - "e2e-feature-gates": panic({0x22a4200, 0x340b020})
generic-1.24: Step #1 - "e2e-feature-gates": 	/usr/local/go/src/runtime/panic.go:890 +0x262
generic-1.24: Step #1 - "e2e-feature-gates": agones.dev/agones/test/e2e/extensions.TestGameServerHealthyAfterDeletingPodWhileOneExtensionsDown(0xc0002f6d00)
generic-1.24: Step #1 - "e2e-feature-gates": 	/go/src/agones.dev/agones/test/e2e/extensions/high_availability_test.go:56 +0x490
generic-1.24: Step #1 - "e2e-feature-gates": testing.tRunner(0xc0002f6d00, 0x258d3f0)
generic-1.24: Step #1 - "e2e-feature-gates": 	/usr/local/go/src/testing/testing.go:1446 +0x217
generic-1.24: Step #1 - "e2e-feature-gates": created by testing.(*T).Run
generic-1.24: Step #1 - "e2e-feature-gates": 	/usr/local/go/src/testing/testing.go:1493 +0x75e
generic-1.24: Step #1 - "e2e-feature-gates": FAIL test/e2e/extensions.TestGameServerHealthyAfterDeletingPodWhileOneExtensionsDown (0.15s)
generic-1.24: Step #1 - "e2e-feature-gates": FAIL test/e2e/extensions
```

**Comment by zmerlynn** [comment]
Presumably also https://github.com/googleforgames/agones/pull/2980#issuecomment-1442143301

**Comment by chiayi** [comment]
So there is a time period right after deleting one of the extensions pod where it still "shows up" on the list and it could be trying to use that extensions pod to create the game server?

**Comment by markmandel** [comment]
Sorry, not sure what "still "shows up" on the list" means in this context. Can you expand? (not familiar with the test at all, so feel free to ignore me if this is obvious to those that are).

**Comment by chiayi** [comment]
Sure, so when I get the list of extensions pods right after calling delete it shows that there are 3 extensions instead of 2. And one of them being the one that was supposed to be deleted. And it takes some time for that extension pod to be no longer on the list.

**Comment by chiayi** [comment]
This also made me realize that it spins up another extension if you delete one, and I'm guessing its because we made the replication '2'?
