### ISSUE TITLE
[Lists]: list(empty) delete values will  be panic   

### ISSUE THREAD

**Issue by GStones** [googleforgames/agones#3614]
### SDK(sidecar)Panic 💣  

**How to reproduce it (as minimally and precisely as possible)**:
 * [FeatureFlag:CountsAndLists]
    remove `Lists` values when  `Lists` empty, SDK(sidecar) will panic   

**Environment**:
- Agones version: 1.37.0
- Kubernetes version (use `kubectl version`): 1.29
- Install method (yaml/helm):  helm
- Troubleshooting guide log(s):      
 ```  text
E0126 12:23:35.015025       1 runtime.go:79] Observed a panic: "makeslice: cap out of range" (runtime error: makeslice: cap out of range)
goroutine 61 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1bcfb80?, 0x22d81d0})
        /go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000061d30?})
        /go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75
panic({0x1bcfb80, 0x22d81d0})
        /usr/local/go/src/runtime/panic.go:884 +0x213
agones.dev/agones/pkg/sdkserver.deleteValues(...)
        /go/src/agones.dev/agones/pkg/sdkserver/sdkserver.go:1241
agones.dev/agones/pkg/sdkserver.(*SDKServer).updateList(0xc00077a1e0, {0x22f8000, 0xc0000ac910})
        /go/src/agones.dev/agones/pkg/sdkserver/sdkserver.go:1205 +0x40f
agones.dev/agones/pkg/sdkserver.(*SDKServer).syncGameServer(0x0?, {0x22f8000?, 0xc0000ac910?}, {0x1e90d8c?, 0xffffffffffffffff?})
        /go/src/agones.dev/agones/pkg/sdkserver/sdkserver.go:353 +0x89
agones.dev/agones/pkg/util/workerqueue.(*WorkerQueue).processNextWorkItem(0xc0000ac730, {0x22f8000, 0xc0000ac910})
        /go/src/agones.dev/agones/pkg/util/workerqueue/workerqueue.go:182 +0x274
agones.dev/agones/pkg/util/workerqueue.(*WorkerQueue).runWorker(...)
        /go/src/agones.dev/agones/pkg/util/workerqueue/workerqueue.go:158
agones.dev/agones/pkg/util/workerqueue.(*WorkerQueue).run.func1()
        /go/src/agones.dev/agones/pkg/util/workerqueue/workerqueue.go:217 +0x45
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
        /go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:226 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x17aeb16?, {0x22dfb80, 0xc000894510}, 0x1, 0xc000542ea0)
        /go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:227 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x0?, 0x0?)
        /go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:204 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/src/agones.dev/agones/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:161
agones.dev/agones/pkg/util/workerqueue.(*WorkerQueue).run(0xc0000ac730?, {0x22f8000?, 0xc0000ac910?})
        /go/src/agones.dev/agones/pkg/util/workerqueue/workerqueue.go:217 +0xdc
created by agones.dev/agones/pkg/util/workerqueue.(*WorkerQueue).Run
        /go/src/agones.dev/agones/pkg/util/workerqueue/workerqueue.go:206 +0x165
panic: runtime error: makeslice: cap out of range [recovered]
        panic: runtime error: makeslice: cap out of range
```

**Comment by GStones** [comment]
Already resolved: https://github.com/googleforgames/agones/pull/3606.

**Comment by igooch** [comment]
Thanks for the fix, although I'm surprised the list not containing the value to delete wasn't caught earlier in the code https://github.com/googleforgames/agones/blob/e88f7c58eb948700637bc4546ff05e642ad67d3a/pkg/sdkserver/sdkserver.go#L1177. How are you calling the list delete?

**Comment by GStones** [comment]
This panic happend before this PR(https://github.com/googleforgames/agones/pull/3606).
 `updateList` not clear, every loop will delete from list
