### ISSUE TITLE
Rust SDK fails to build in Docker container as expected

### ISSUE THREAD

**Issue by matty-kuhn** [googleforgames/agones#3727]
**RESOLVED**
Leaving this up in case others have the same issue: on alpine, be sure to install protobuf AND protobuf-dev, on ubuntu you should just need protobuf-compiler (this package is hopelessly out of date though)

**What happened**:

I am trying to integrate the agones sdk into a simple tonic echo server, and when i build it normally (cargo build) it works fine, but when I try to run the same cargo build in a docker image, the agones `build.rs` cannot find any of it's proto files that it needs to build.

**What you expected to happen**: 

I expected that it should have simply built the binary

**How to reproduce it (as minimally and precisely as possible)**:

I am building a the minimal tonic example [echo server](https://github.com/hyperium/tonic/tree/master/examples/src/streaming) in the rust:alpine docker image, targeting x86_64-musl (but the same thing happens on ubuntu targeting gnu).

**Anything else we need to know?**:

From looking at the rust-example, it looks like you copy the sdk into the builder, so is the preferred use-case for the sdk to be a submodule in-tree? if that is the case why publish it to crates.io? I'm guessing i'm just using it wrong, but the example not using the version in crates.io is a little confusing

**Environment**:
- Agones version: 1.39.0, but I tried dropping the version as low as 1.0.0 and it still didn't work 
- Kubernetes version (use `kubectl version`): 1.28.3
- Cloud provider or hardware configuration: running locally on minikube, but i never make it that far since it won't build
- Install method (yaml/helm): N/a
- Troubleshooting guide log(s): N/a won't build
- Others:
**EDIT:**
Here is the backtrace:
```
thread 'main' panicked at agones-sdk/build.rs:14:10:
11.33   failed to compile protobuffers: Custom { kind: Other, error: "protoc failed: google/protobuf/descriptor.proto: File not found.\ngoogle/api/annotations.proto:20:1: Import \"google/protobuf/descriptor.proto\" was not found or had errors.\ngoogle/api/annotations.proto:28:8: \"google.protobuf.MethodOptions\" is not defined.\ngoogle/protobuf/duration.proto: File not found.\ngoogle/api/client.proto:20:1: Import \"google/protobuf/descriptor.proto\" was not found or had errors.\ngoogle/api/client.proto:21:1: Import \"google/protobuf/duration.proto\" was not found or had errors.\ngoogle/api/client.proto:278:5: \"google.protobuf.Duration\" is not defined.\ngoogle/api/client.proto:287:5: \"google.protobuf.Duration\" is not defined.\ngoogle/api/client.proto:291:5: \"google.protobuf.Duration\" is not defined.\ngoogle/api/client.proto:29:8: \"google.protobuf.MethodOptions\" is not defined.\ngoogle/api/client.proto:68:8: \"google.protobuf.ServiceOptions\" is not defined.\ngoogle/api/client.proto: \"google.protobuf.ServiceOptions\" is not defined.\ngoogle/api/field_behavior.proto:19:1: Import \"google/protobuf/descriptor.proto\" was not found or had errors.\ngoogle/api/field_behavior.proto:27:8: \"google.protobuf.FieldOptions\" is not defined.\ngoogle/api/resource.proto:19:1: Import \"google/protobuf/descriptor.proto\" was not found or had errors.\ngoogle/api/resource.proto:28:8: \"google.protobuf.FieldOptions\" is not defined.\ngoogle/api/resource.proto:34:8: \"google.protobuf.FileOptions\" is not defined.\ngoogle/api/resource.proto:40:8: \"google.protobuf.MessageOptions\" is not defined.\ngoogle/protobuf/empty.proto: File not found.\ngoogle/protobuf/field_mask.proto: File not found.\ngoogle/protobuf/wrappers.proto: File not found.\ngoogle/protobuf/struct.proto: File not found.\nprotoc-gen-openapiv2/options/openapiv2.proto:5:1: Import \"google/protobuf/struct.proto\" was not found or had errors.\nprotoc-gen-openapiv2/options/openapiv2.proto: \"google.protobuf.Value\" is not defined.\nprotoc-gen-openapiv2/options/openapiv2.proto: \"google.protobuf.Value\" is not defined.\nprotoc-gen-openapiv2/options/openapiv2.proto: \"google.protobuf.Value\" is not defined.\nprotoc-gen-openapiv2/options/openapiv2.proto: \"google.protobuf.Value\" is not defined.\nprotoc-gen-openapiv2/options/openapiv2.proto: \"google.protobuf.Value\" is not defined.\nprotoc-gen-openapiv2/options/openapiv2.proto: \"google.protobuf.Value\" is not defined.\nprotoc-gen-openapiv2/options/annotations.proto:5:1: Import \"google/protobuf/descriptor.proto\" was not found or had errors.\nprotoc-gen-openapiv2/options/annotations.proto:6:1: Import \"protoc-gen-openapiv2/options/openapiv2.proto\" was not found or had errors.\nprotoc-gen-openapiv2/options/annotations.proto:10:8: \"google.protobuf.FileOptions\" is not defined.\nprotoc-gen-openapiv2/options/annotations.proto:17:8: \"google.protobuf.MethodOptions\" is not defined.\nprotoc-gen-openapiv2/options/annotations.proto:24:8: \"google.protobuf.MessageOptions\" is not defined.\nprotoc-gen-openapiv2/options/annotations.proto:31:8: \"google.protobuf.ServiceOptions\" is not defined.\nprotoc-gen-openapiv2/options/annotations.proto:38:8: \"google.protobuf.FieldOptions\" is not defined.\nalpha.proto:20:1: Import \"google/api/annotations.proto\" was not found or had errors.\nalpha.proto:21:1: Import \"google/api/client.proto\" was not found or had errors.\nalpha.proto:22:1: Import \"google/api/field_behavior.proto\" was not found or had errors.\nalpha.proto:23:1: Import \"google/api/resource.proto\" was not found or had errors.\nalpha.proto:24:1: Import \"google/protobuf/empty.proto\" was not found or had errors.\nalpha.proto:25:1: Import \"google/protobuf/field_mask.proto\" was not found or had errors.\nalpha.proto:26:1: Import \"google/protobuf/wrappers.proto\" was not found or had errors.\nalpha.proto:27:1: Import \"protoc-gen-openapiv2/options/annotations.proto\" was not found or had errors.\nalpha.proto:239:3: \"google.protobuf.Int64Value\" is not defined.\nalpha.proto:241:3: \"google.protobuf.Int64Value\" is not defined.\nalpha.proto:299:3: \"google.protobuf.FieldMask\" is not defined.\n" }
11.33   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
11.33 warning: build failed, waiting for other jobs to finish...
12.92 thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-chef-0.1.66/src/recipe.rs:218:27:
12.92 Exited with status code: 101
12.92 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Luminoth** [comment]
I'm confused, why is this closed without any comments? I'm running into the same issue and have the same question, are we supposed to have the entire SDK in tree instead of using the crates.io version? None of this is covered in the [guide](https://agones.dev/site/docs/guides/client-sdks/rust/).
